apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todobackend
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: front=cr.yandex/crpeavbuog9kpj9315jh/anchetin/todobackend
    argocd-image-updater.argoproj.io/front.update-strategy: latest
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: todobackend
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/todobackend
    # Обратите внимание, что адрес поменялся – это новый параметр
    repoURL: {{ .Values.spec.source.appsRepoURL }}
    targetRevision: {{ .Values.spec.source.appsTargetRevision }}
    helm:
      valueFiles:
        # Указываем новый путь до только что созданного ключа
        - secrets+age-import:///helm-secrets-private-keys-apps/key.txt?secrets.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true