apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbinprod
  labels:
    app: httpbinprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbinprod
  template:
    metadata:
      labels:
        app: httpbinprod
    spec:
      containers:
        - name: httpbinprod
          image: kong/httpbin:latest
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbinprod
spec:
  type: NodePort
  selector:
    app: httpbinprod
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbinprod
  annotations:
    ingress.alb.yc.io/subnets: {{ .Values.alb.subnetId }}
    ingress.alb.yc.io/external-ipv4-address: {{ .Values.alb.externalipv4address }}
    ingress.alb.yc.io/group-name: {{ .Values.alb.groupname }}
    ingress.alb.yc.io/security-groups: {{ .Values.alb.securitygroups }}
spec:
  tls:
    - hosts:
        - "httpbin.apps.ychetloud.ru"
      secretName: yc-certmgr-cert-id-{{ .Values.certificateId }}
  rules:
    - host: httpbin.apps.ychetloud.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbinprod
                port:
                  number: 80