apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "yc-alb-ingress-controller.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  YC_ALB_FOLDER_ID: {{ .Values.folderId }}
  YC_ALB_CLUSTER_ID: {{ include "validateClusterID" .Values.clusterId }}
  YC_ENDPOINT: {{ .Values.endpoint }}
  YC_ALB_REGION: {{ include "validateRegionFunc" .Values.region | quote }}