apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbuser.name }}
  namespace: infrastructure
type: Opaque
data:
  password: {{ .Values.dbuser.password64 }} 
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlCluster
metadata:
  name: {{ include "clusterFullName" . }}
spec:
  forProvider:
    name: {{ include "clusterFullName" . }}
    environment: {{ .Values.environment }}
    networkIdRef:
      name: default
    config:
      - version: "12"
        resources:
          - diskSize: 16
            diskTypeId: network-hdd
            resourcePresetId: s2.micro
        postgresqlConfig:
          max_connections: "395"
          enable_parallel_hash: "true"
          vacuum_cleanup_index_scale_factor: "0.2"
          autovacuum_vacuum_scale_factor: "0.34"
          default_transaction_isolation: "TRANSACTION_ISOLATION_READ_COMMITTED"
          shared_preload_libraries: SHARED_PRELOAD_LIBRARIES_AUTO_EXPLAIN
        # access:
        #   - websql: true
    maintenanceWindow:
      - type: WEEKLY
        day: SAT
        hour: 12
    host:
      - zone: {{ .Values.zone }}
        subnetIdRef:
          name: default
    folderIdRef:
      name: default
    securityGroupIdsRefs:
      - name: db-security-group
#---
# Do not work unfortunately
 
# apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
# kind: PostgresqlUser
# metadata:
#   name: {{ .Values.dbuser.name }}
# spec:
#   forProvider:
#       clusterIdRef: 
#         name: {{ include "clusterFullName" . }}
#       name: {{ .Values.dbuser.name }}
#       passwordSecretRef:
#         name: {{ .Values.dbuser.name }}
#         key: password
#         namespace: infrastructure
#       connLimit: 50
#       settings:
#         default_transaction_isolation: "read committed"
#         log_min_duration_statement: "5000"
# ---
# apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
# kind: PostgresqlDatabase
# metadata:
#   name: {{ .Values.dbname }}
# spec:
#   forProvider:
#       clusterIdRef: 
#         name: {{ include "clusterFullName" . }}
#       name: {{ .Values.dbname }}
#       owner: {{ .Values.dbuser.name }}       