subnetId: ENC[AES256_GCM,data:SzbVfa6vKr4gYV7J2auOki3ulc4=,iv:x+fLFrzTdVbS+MQ2l+ett72dtraycbxl4wEj+/YW+S4=,tag:U/8nH80GuEgFqotWpisQtQ==,type:str]
certificateId: ENC[AES256_GCM,data:zEGCjes2nNMkOXFQmqXhst+q8eQ=,iv:OXCCGMzlYUq098elWvQv3AZ+U8/Z928eTStr6E4Oa3M=,tag:5gaFGYd5V2PJaKe/dZU2Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3tw6ssuv8q9t9wfhrvhrztzdfl0k784ksjzj77f0wmqjsjgvuhqkc5xp5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb2hZN1k1ZlB5MUtvOFpj
            KzcwQytySVdwY0d0WkVWbDhFcE1QZUdRSHgwClFTUGRJRVRYaWhKME0zQWNSb0FG
            SlBKMVdxdlcyRU94eTZBZlc5MkJuSHMKLS0tIDcwQVBoNHhReG1qSUszN1B3U0hR
            LzZ6RXA5WGVRRFJ2UHZQb3FPSXk4U0EKAGt2sAosSA/hpcbhg2ZydIUzr0GM4nFc
            hBy+jnJsAflS8NCQ2ljpS6bauFeof0bZerIjU7PGiMoICzIluSe4jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T03:55:21Z"
    mac: ENC[AES256_GCM,data:lBZN/X66cGnIyDXfKFc97Lhx2/+Rnrs6ywL2YHX0NyON9f2RmQXH6ThPFUrARKJSyV0Ui9r4Nan+UDWjGI8w4+5+yw3jxdNSbq9SvRFTTQTv7bUwQIL9zne0VKXDLDuC4M1qEgKRuOZv8TFP2QmdlaRifflwk1/HUlZyx4cDwkI=,iv:fZkgGy48q6XeszOxJ2XfGFmWDAWlio4nwCrmnYioC38=,tag:jJNu+oXelhOBDfi2CIZKvQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
